### ISSUE TITLE
自动打开后不点击红包的“开”按钮，回到本应用，然后再返回微信，就能点击了

### ISSUE THREAD

**Issue by spring-zs** [xbdcc/GrabRedEnvelope#11]
如题，每次都能打开，但是不点击“开”，然后回到本应用界面（什么也不做），再返回。就能点击“开”了。。但是，如果再有红包，仍然需要重复这样的过程。
另外，微信目前最新是7.0.21  ，id 和7.0.19是一样的，但是和7.0.16版本不同。。如下：
"7.0.19" -> {
                RED_ENVELOPE_TITLE_ID = "com.tencent.mm:id/cyv" //首页底面小文字的id
                RED_ENVELOPE_RECT_TITLE_ID = "com.tencent.mm:id/cyv" //首页底面小文字的id
                RED_ENVELOPE_ID = "com.tencent.mm:id/al7" //聊天界面红包item点击框控件id

                RED_ENVELOPE_FLAG_ID = "com.tencent.mm:id/ra" //聊天页面区分红包id
                RED_ENVELOPE_OPEN_ID = "com.tencent.mm:id/den" //抢红包页面点开控件id
                RED_ENVELOPE_CLOSE_ID = "com.tencent.mm:id/dem" //抢红包页面退出控件id
                RED_ENVELOPE_BEEN_GRAB_ID = "com.tencent.mm:id/r0" //聊天页面检测红包已被领控件id
                /* 红包详情页控件 */
                RED_ENVELOPE_COUNT_ID = "com.tencent.mm:id/d4y" //红包金额id

            }

旧手机荣耀7一切正常，但是荣耀9x不行。。。

可能是sdk版本问题 android 系统问题？

**Comment by spring-zs** [comment]
grabRedEnvelope()中if里的函数不会点击红包的“开”按钮
if (findAndClickFirstNodeInfoByViewId(
                RED_ENVELOPE_ID, RED_ENVELOPE_FLAG_ID, RED_ENVELOPE_BEEN_GRAB_ID, !ifGrabSelf, true
            )

**Comment by xbdcc** [comment]
目前应该都升级至8.0.0了，昨天刚更新的3.3.0版本新版本支持8.0.0：https://github.com/xbdcc/GrabRedEnvelope/releases/download/3.3.0/GrabRedEnvelope3.3.0.apk 支持微信8.0.0，可升级试试。
