### ISSUE TITLE
红米10x 安卓10 不行（微信红包监控开关一直打不开，但是已经开启辅助功能）

### ISSUE THREAD

**Issue by OtisZhang** [xbdcc/GrabRedEnvelope#14]
![5161613019521_ pic_hd](https://user-images.githubusercontent.com/53670773/107603912-4a5e6c00-6c69-11eb-8278-495c68656d54.jpg)
![5171613019522_ pic_hd](https://user-images.githubusercontent.com/53670773/107603922-4fbbb680-6c69-11eb-8950-3474276a17d3.jpg)
![5181613019523_ pic_hd](https://user-images.githubusercontent.com/53670773/107603934-606c2c80-6c69-11eb-99b9-33cd71c76f88.jpg)

**Comment by xbdcc** [comment]
3.4.0新版本试试
