### ISSUE TITLE
最新版本支持华为，但是不支持小米8

### ISSUE THREAD

**Issue by robin-fei** [xbdcc/GrabRedEnvelope#2]
描述如下：
1、红包到达小米8微信聊天界面，可以打开红包，但是没有拆开红包，且没有关闭红包详情页

**Comment by xbdcc** [comment]
谢谢反馈，之前是拿自己oppo r9手机开发的，没其他机型，后面找到类似机型找下问题尝试修复。

**Comment by xbdcc** [comment]
> 描述如下：
> 1、红包到达小米8微信聊天界面，可以打开红包，但是没有拆开红包，且没有关闭红包详情页



> 描述如下：
> 1、红包到达小米8微信聊天界面，可以打开红包，但是没有拆开红包，且没有关闭红包详情页

谢谢反馈，之前是拿自己oppo r9手机开发的，没其他机型，后面找到类似机型找下问题尝试修复。

**Comment by xbdcc** [comment]
> 描述如下：
> 1、红包到达小米8微信聊天界面，可以打开红包，但是没有拆开红包，且没有关闭红包详情页

谢谢反馈，之前是拿自己oppo r9手机开发的，没其他机型，后面找到类似机型找下问题尝试修复。

**Comment by xbdcc** [comment]
> 描述如下：
> 1、红包到达小米8微信聊天界面，可以打开红包，但是没有拆开红包，且没有关闭红包详情页

新版本2.1.0应该修复了这个问题了，可以再试下。
