### ISSUE TITLE
关于进程

### ISSUE THREAD

**Issue by Aashaby** [xbdcc/GrabRedEnvelope#25]
能不能参考这个https://blog.csdn.net/fangqiangqi/article/details/51518301防止进程被杀死

**Comment by xbdcc** [comment]
好的，谢谢，后面版本看看

**Comment by Aashaby** [comment]
https://blog.csdn.net/tobacco5648/article/details/70247692
https://www.cnblogs.com/ningskyer/articles/9389670.html

**Comment by yuther** [comment]
华为emu 9无效

**Comment by sunlinebox** [comment]
做一个前台通知，不容易被kill

**Comment by android-greenhand** [comment]
可以提高WechatService的优先级

**Comment by moyueheng** [comment]
红米10x无效

**Comment by xbdcc** [comment]
已发布新版本，新版本再试下
