### ISSUE TITLE
下载地址打开说需要备案

### ISSUE THREAD

**Issue by skycityzy** [xbdcc/GrabRedEnvelope#29]
![image](https://user-images.githubusercontent.com/71860806/157785483-f922f384-201f-496d-b69d-8c3b03c289fb.png)

**Comment by ProfessorX** [comment]
同上，网站没备案吧。

看博主愿意备案不，我的反正搞个域名挂在 github.io 

以前搞wordpress，现在wordpress都懒得搞了。

**Comment by xbdcc** [comment]
已正常
