### ISSUE TITLE
小米8 安卓9   只能点开红包不自动抢

### ISSUE THREAD

**Issue by luoyu86** [xbdcc/GrabRedEnvelope#3]
是哪里设置不对吗   微信版本7.05

**Comment by xbdcc** [comment]
> 是哪里设置不对吗 微信版本7.05

安装的是前几天更新的2.1.0新版本的APK吗？如果不是的话试试这个版本，记得好像好不容易找到该机型测试过一次可以改过。
如果还是不行的话可以告知下手机dpi和弹出来的按钮的大致点击坐标点范围吗？或者在项目代码WechatService类里的openRedEnvelopeNew你可以改了测试下可以push下。

**Comment by xbdcc** [comment]
> 是哪里设置不对吗 微信版本7.05

也可以在这上面留言讨论哈：https://gitter.im/xbdcc/GrabRedEnvelope

**Comment by dhz20911** [comment]
vivo x6 x7  锁屏不抢 要手动解屏才能，刚装时可以了 一天就不行了，重装也不行，后台，通知都设置了

**Comment by kwu130** [comment]
v2.2.0(2019.12.31)在微信7.0.10上只能打开红包，不能自动点击"开"红包。测试机型redmi k20

**Comment by Micalson** [comment]
我今天也试了v2.2.0，在微信7.0.9上只能打开红包，不能自动点击“开”红包，测试机型位小米8.

**Comment by luogangZERO** [comment]
小米8的dpi440，WechatService类里的openRedEnvelopeNew设置为path.moveTo(540f, 1465f)就可以了

**Comment by sailsgo** [comment]
辣鸡啊，打开，不自动抢

**Comment by RiggTIan** [comment]
> 辣鸡啊，打开，不自动抢

免费的还嫌垃圾？有能耐你整一个牛逼的好吧

**Comment by RiggTIan** [comment]
> v2.2.0(2019.12.31)在微信7.0.10上只能打开红包，不能自动点击"开"红包。测试机型redmi k20

+1
v2.2.0  微信7.0.10  安卓10.0  MIUI 11.0.5 
机型:Redmi K20 Pro

**Comment by RiggTIan** [comment]
3.0.0自定义坐标完美解决问题

**Comment by xbdcc** [comment]
嗯，3.0.0版本加了自定义拆红包坐标点来解决部分机型的这个问题。
