### ISSUE TITLE
MIUI 12.5 开启辅助权限后微信监控开关还是没有打开

### ISSUE THREAD

**Issue by Shaun-Yao** [xbdcc/GrabRedEnvelope#30]
在小米手机上多次尝试仍无法使用

**Comment by testfreeuser** [comment]
需要在手机管家里，把这个APP的“后台”高耗电自动关闭，“自动启动”高耗电 自动关闭，这两项的勾去掉，还要在这个APP的用电策略里，设置成 不限制。 你再去启动这个APP的无障碍服务，就不会被自动关闭了。
你把微信的新消息通知，手机系统设置的微信通知权限，都要打开。 你微信群里的需要启动抢红包的群，设置 消息免打扰 这项为关闭。

**Comment by xbdcc** [comment]
> 需要在手机管家里，把这个APP的“后台”高耗电自动关闭，“自动启动”高耗电 自动关闭，这两项的勾去掉，还要在这个APP的用电策略里，设置成 不限制。 你再去启动这个APP的无障碍服务，就不会被自动关闭了。 你把微信的新消息通知，手机系统设置的微信通知权限，都要打开。 你微信群里的需要启动抢红包的群，设置 消息免打扰 这项为关闭。

谢谢帮忙解答，确实有些手机管家会自动拦截权限，需要加入白名单或手动打开
