### ISSUE TITLE
这个自动发送表情消息，是第一次进聊天窗口时会发送的表情消息，没意义。

### ISSUE THREAD

**Issue by testfreeuser** [xbdcc/GrabRedEnvelope#32]
这个自动发送表情消息，是第一次进聊天窗口时会发送的表情消息，没意义。 为什么不是抢红包后，如果抢成功，自动艾特发红包的人发送表情消息呢？

**Comment by xbdcc** [comment]
> 这个自动发送表情消息，是第一次进聊天窗口时会发送的表情消息，没意义。 为什么不是抢红包后，如果抢成功，自动艾特发红包的人发送表情消息呢？

做这个是之前新表情出来时连续放烟花的效果，意义是不一样
