### ISSUE TITLE
试用还发现一个问题，对于没点过的，但已经被人抢光的红包，自动点击后，不会进详情页，所以，不会自动退出。

### ISSUE THREAD

**Issue by testfreeuser** [xbdcc/GrabRedEnvelope#33]
没点过的红包，会自动点击， 如果自动抢到了红包，会进详情页，停留指定时间后，会自动返回微信界面。
但是如果没抢到，则会一直停留在，手慢了，红包已经被派完，这个界面，不会自动返回微信界面。

**Comment by xbdcc** [comment]
已知问题，消息冲掉就可以了
