### ISSUE TITLE
博主已经不维护了吗？升级到微信8.0.24后，不能监控聊天列表，不能统计红包金额了。

### ISSUE THREAD

**Issue by testfreeuser** [xbdcc/GrabRedEnvelope#34]
可能是微信8.0.24的聊天列表界面控件ID，红包金额控件ID，发生了变化。博主不维护更新以下么。

**Comment by xbdcc** [comment]
> 可能是微信8.0.24的聊天列表界面控件ID，红包金额控件ID，发生了变化。博主不维护更新以下么。

业余学习项目，偶尔维护，暂时不更新，年终放假期间会抽空更新

**Comment by xbdcc** [comment]
> 可能是微信8.0.24的聊天列表界面控件ID，红包金额控件ID，发生了变化。博主不维护更新以下么。

新版本已更新
