### ISSUE TITLE
华为p30软件不起作用呢

### ISSUE THREAD

**Issue by sennnnnnn** [xbdcc/GrabRedEnvelope#35]
![1321667537869_ pic](https://user-images.githubusercontent.com/26957654/199891283-8a90eb0c-9e99-41f7-9e73-519118a5a52e.jpg)
![1331667537934_ pic](https://user-images.githubusercontent.com/26957654/199891290-e4f3f3f0-3e1f-444a-b7c1-cd60d8383db8.jpg)
里面设置了微信抢红包外面这个是否开启状态还是未开始正常吗？

**Comment by xbdcc** [comment]
新版本试试
