### ISSUE TITLE
本软件设定使用时限已到时间

### ISSUE THREAD

**Issue by SStarver** [xbdcc/GrabRedEnvelope#36]
求问，P40 尝鲜不可用啊，提示“本软件设定使用时限已到时间，谢谢使用，请点击确定退出，如想继续使用可联系小不点，谢谢！”

博主有空可以给解答下吗？

**Comment by WenjiaRan** [comment]
直接在源代码里找到相应位置，把软件使用时限延改一下，再重新打包成apk就行了

**Comment by longbaohe** [comment]
博主人呢

**Comment by longbaohe** [comment]
@xbdcc

**Comment by noneGenious** [comment]
> 求问，P40 尝鲜不可用啊，提示“本软件设定使用时限已到时间，谢谢使用，请点击确定退出，如想继续使用可联系小不点，谢谢！”
> 
> 博主有空可以给解答下吗？



> 博主人呢

自己看源码改啊又不是没给你源码，别做伸手党

**Comment by SStarver** [comment]
博主已更新代码
