### ISSUE TITLE
Jiguang 提示：包名和appkey不匹配

### ISSUE THREAD

**Issue by SStarver** [xbdcc/GrabRedEnvelope#39]
请问有没有人遇到：
自己拉最新代码编译安装后报“Jiguang 提示：包名和appkey不匹配” ？
没搞过安卓开发，自己查也没查到有效的解决办法，求助

**Comment by xbdcc** [comment]
> 请问有没有人遇到：
> 
> 自己拉最新代码编译安装后报“Jiguang 提示：包名和appkey不匹配” ？
> 
> 没搞过安卓开发，自己查也没查到有效的解决办法，求助

不改包名的情况下应该不会出现吧，我最近在调代码都是正常的，如果不熟悉Android可以直接注释掉代码里这块初始化不影响功能

**Comment by fengyichui** [comment]
我重新编译后安装也是提示这个，改的地方就是把时间限制取消。

**Comment by xbdcc** [comment]
> 我重新编译后安装也是提示这个，改的地方就是把时间限制取消。

拉最新代码出现的吗？回退十点多前的编译安装正常吗

**Comment by SStarver** [comment]
>

**Comment by fengyichui** [comment]
我上个星期拉的代码测试出现的，最新的还没试过。

**Comment by SStarver** [comment]
> > 我重新编译后安装也是提示这个，改的地方就是把时间限制取消。
> 
> 拉最新代码出现的吗？回退十点多前的编译安装正常吗

我昨天拉的代码编译报这个，今天看博主更新代码了，就拉了最新的试了下还是有这个报错。

表示之前写C的，java 完全看不懂哇，求博主指点下具体注释哪一行呢

**Comment by xbdcc** [comment]
> > > 我重新编译后安装也是提示这个，改的地方就是把时间限制取消。
> 
> > 
> 
> > 拉最新代码出现的吗？回退十点多前的编译安装正常吗
> 
> 
> 
> 我昨天拉的代码编译报这个，今天看博主更新代码了，就拉了最新的试了下还是有这个报错。
> 
> 
> 
> 表示之前写C的，java 完全看不懂哇，求博主指点下具体注释哪一行呢

可以注释掉MyApplication类的AppInit这一行，我没遇到过，贴下错误的地方日志我看下，这两天调下后拉新代码再试试

**Comment by SStarver** [comment]
手机通知栏提示的错误信息，看了下日志，像是对应下面的报错，第一次完安卓studio, 不排除是自己编译过程操作的错误哈~：
E/JIGUANG-JCore: [CheckManifestHelper] [key-step]errorcode:10001,metadata: JCore appKey - not defined in manifest
I/UMConfigure: channel is 3.4.1
D/JIGUANG-JPush: [ActionHelper] doAction:jcore_on_event
I/JIGUANG-JCore: [JCoreGobal] [key-step]service process init - jcore, SdkVersion:4.0.0, build id:204 build type:release
E/JIGUANG-JCore: [CheckManifestHelper] [key-step]errorcode:10001,metadata: JCore appKey - not defined in manifest
D/JIGUANG-JPush: [ActionHelper] doAction:jcore_on_event
I/JIGUANG-JCore: [JCoreGobal] [key-step]service process init - jcore, SdkVersion:4.0.0, build id:204 build type:release
E/JIGUANG-JCore: [CheckManifestHelper] [key-step]errorcode:10001,metadata: JCore appKey - not defined in manifest
D/JIGUANG-JPush: [ActionHelper] doAction:jcore_on_event
I/UMLog: 统计SDK初始化成功
E/UMLog: ┌───────────────────问题─────────────────────────────────────────────────────────────────────────────
E/UMLog: │     AppKey不能为空
E/UMLog: ├───────────────────解决方案─────────────────────────────────────────────────────────────────────────────
E/UMLog: │     您必须正确设置AppKey，如何正确初始化请详见地址：https://developer.umeng.com/docs/66632/detail/67292?um_channel=sdk
E/UMLog: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/MobclickAgent: setPageCollectionMode can not be called in child process

**Comment by SStarver** [comment]
> > > > 我重新编译后安装也是提示这个，改的地方就是把时间限制取消。
> > 
> > 
> > > 
> > 
> > 
> > > 拉最新代码出现的吗？回退十点多前的编译安装正常吗
> > 
> > 
> > 我昨天拉的代码编译报这个，今天看博主更新代码了，就拉了最新的试了下还是有这个报错。
> > 表示之前写C的，java 完全看不懂哇，求博主指点下具体注释哪一行呢
> 
> 可以注释掉MyApplication类的AppInit这一行，我没遇到过，贴下错误的地方日志我看下，这两天调下后拉新代码再试试

try and try， 还是不行，日志好像不报了，但是手机通知栏还是会跳。坐等博主release apk~

**Comment by weberrr** [comment]
求 apk

**Comment by xbdcc** [comment]
> 

刚更新了代码，拉下新代码编译应该没问题了

**Comment by weberrr** [comment]
> > 
> 
> 刚更新了代码，拉下新代码编译应该没问题了

可以发布个编译好的吗，求
