### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Ricemeal** [xbdcc/GrabRedEnvelope#4]
老师你好，我看到你在wechat_service.xml文件描述了“在9.0中会无法监听通知内容”，是指AccessibilityService无法监听通知栏的消息吗？还有这个9.0是指哪个？我最近刚接触这个，想实现自动微信回复，发现无法监听消息内容。不知道能否讨教一番。

**Comment by Ricemeal** [comment]
Android studio 3.5.2；JDK8;

**Comment by Ricemeal** [comment]
Android SDK 应该用的是API 25

**Comment by xbdcc** [comment]
> 老师你好，我看到你在wechat_service.xml文件描述了“在9.0中会无法监听通知内容”，是指AccessibilityService无法监听通知栏的消息吗？还有这个9.0是指哪个？我最近刚接触这个，想实现自动微信回复，发现无法监听消息内容。不知道能否讨教一番。

9.0指的Android9.0的系统，9.0以下机型在xml中限定packageNames字段会正常监听，9.0的用AccessibilityService的话需要在xml里面去掉这个字段，可以在AccessibilityService类里面用代码做过滤监听应用。
stackoverflow的这个问题描述的就是这个场景：https://stackoverflow.com/questions/55472464/type-notification-state-changed-event-is-not-getting-received-by-accessibility-s

**Comment by Ricemeal** [comment]
最后，我重新装了个安卓模拟器，验证当前的代码的Accessibility可以实现微信消息的监听。遗憾的是，在我的MI6(android 7.1.1)上仍然不起作用(微信都是同一个版本)。也许是MIUI系统的问题，也可能是我刷过magsik，也有可能是运行了Wxposed。希望能给有需要的人提供一定参考。
