### ISSUE TITLE
麻烦release最新版

### ISSUE THREAD

**Issue by maybe-why-not** [xbdcc/GrabRedEnvelope#40]
今天这个app先学到这了，/(ㄒoㄒ)/~~
![image](https://user-images.githubusercontent.com/29968903/213528568-22927928-ee0d-411f-b695-67f7e256ff5e.png)

**Comment by weberrr** [comment]
+1 求apk

**Comment by 1781429734** [comment]
加油

**Comment by xbdcc** [comment]
已更新
