### ISSUE TITLE
自定义拆红包的坐标如何设置

### ISSUE THREAD

**Issue by jakefeng0090** [xbdcc/GrabRedEnvelope#46]
不是很明白坐标应该如何设置，求解答谢谢

**Comment by xbdcc** [comment]
百度搜索自己手机机型打开开发者选项的方法，然后进入开发者选项打开指针位置，触摸时会显示x,y坐标点
如果上面方法不会可以看自己手机分辨率多少，肉眼估计或拿尺按比例换算
