### ISSUE TITLE
oppoA79

### ISSUE THREAD

**Issue by StevenHX** [xbdcc/GrabRedEnvelope#5]
请问一下，oppo手机，新消息来了之后，AccessibilityEvent.TYPE_NOTIFICATION_STATE_CHANGED，一直不会被调用，有遇到过这样的问题吗？

**Comment by Ricemeal** [comment]
好像跟我的情况一样。你可以尝试csdn上一篇关于notificationlistener和Android auto的文章



---Original---

**Comment by xbdcc** [comment]
> 请问一下，oppo手机，新消息来了之后，AccessibilityEvent.TYPE_NOTIFICATION_STATE_CHANGED，一直不会被调用，有遇到过这样的问题吗？

参考这个：https://github.com/xbdcc/GrabRedEnvelope/issues/4
