### ISSUE TITLE
点开红包问题

### ISSUE THREAD

**Issue by lds2320199213** [xbdcc/GrabRedEnvelope#7]
本人华为手机：弹出红包页面之后，需要二次进入页面才可以自动打开红包；换言之，华为手机无法打开红包；我只测试了华为手机，其他的不清楚

**Comment by Skippper** [comment]
我的是vivo iqoo3  微信版本7.0.16 下载app版本 3.20  使用app只能监控到弹出红包页面但是无法自动领取

**Comment by FMZHOU** [comment]
> 本人华为手机：弹出红包页面之后，需要二次进入页面才可以自动打开红包；换言之，华为手机无法打开红包；我只测试了华为手机，其他的不清楚

我也是

**Comment by xbdcc** [comment]
> 本人华为手机：弹出红包页面之后，需要二次进入页面才可以自动打开红包；换言之，华为手机无法打开红包；我只测试了华为手机，其他的不清楚

新版本3.3.0重新适配了：https://github.com/xbdcc/GrabRedEnvelope/releases/download/3.3.0/GrabRedEnvelope3.3.0.apk
